workflows:
  memory-card-workflow:
    name: MemoryCard
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Memory Card API
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.MindForge
      vars:
        BUNDLE_ID: "com.MindForge"
        XCODE_SCHEME: "MemoryCard"
        APP_STORE_APPLE_ID: 6757203309
        # Явно указываем новую версию
        NEW_MARKETING_VERSION: "1.1"
      xcode: latest
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      
      - name: Force update version in ALL Info.plist files
        script: |
          cd $CM_BUILD_DIR
          echo "=== FORCE UPDATING VERSION TO $NEW_MARKETING_VERSION ==="
          
          # Находим ВСЕ Info.plist файлы в проекте
          find . -name "Info.plist" -type f | while read plist; do
            echo "Updating: $plist"
            
            # Сохраняем старую версию
            OLD_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$plist" 2>/dev/null || echo "1.0")
            echo "  Old version: $OLD_VERSION"
            
            # Устанавливаем новую версию
            /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $NEW_MARKETING_VERSION" "$plist"
            
            # Увеличиваем build number на 1
            OLD_BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$plist" 2>/dev/null || echo "1")
            NEW_BUILD=$((OLD_BUILD + 1))
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$plist"
            
            NEW_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$plist")
            NEW_BUILD_CHECK=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$plist")
            echo "  New version: $NEW_VERSION (build: $NEW_BUILD_CHECK)"
            echo "  ---"
          done
          
          # Также обновляем через agvtool на всякий случай
          echo "=== Updating via agvtool ==="
          agvtool new-marketing-version $NEW_MARKETING_VERSION
          agvtool new-version -all $(($(agvtool what-version -terse1 2>/dev/null || echo "1") + 1))
          
          echo "=== FINAL CHECK ==="
          echo "Marketing version: $(agvtool what-marketing-version 2>/dev/null || echo 'agvtool failed')"
          echo "Build version: $(agvtool what-version 2>/dev/null || echo 'agvtool failed')"
          
          # Дополнительная проверка первого найденного Info.plist
          SAMPLE_PLIST=$(find . -name "Info.plist" -type f | head -1)
          if [ -f "$SAMPLE_PLIST" ]; then
            echo "Sample Info.plist content:"
            echo "  Version: $(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$SAMPLE_PLIST")"
            echo "  Build: $(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$SAMPLE_PLIST")"
          fi
      
      - name: Build ipa for distribution
        script: |
          echo "=== Building IPA ==="
          echo "Expected version should be: $NEW_MARKETING_VERSION"
          
          xcode-project build-ipa \
            --project "MemoryCard.xcodeproj" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
