workflows:
  memory-card-workflow:
    name: MemoryCard
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Memory Card API
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.MindForge
      vars:
        BUNDLE_ID: "com.MindForge"
        XCODE_SCHEME: "MemoryCard"
        APP_STORE_APPLE_ID: 6757203309
        # ЯВНО указываем версии - не надеемся на скрипт
        NEW_MARKETING_VERSION: "1.2"
        NEW_BUILD_NUMBER: "2"  # Явно указываем 2 или 3
      xcode: latest
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      
      - name: DEBUG: Проверить что есть
        script: |
          cd $CM_BUILD_DIR
          echo "=== DEBUG: ПРОЕКТ ==="
          echo "Директория: $(pwd)"
          ls -la
          echo "=== Info.plist файлы ==="
          find . -name "Info.plist" -type f
          echo "=== Содержимое первого Info.plist ==="
          FIRST=$(find . -name "Info.plist" -type f | head -1)
          if [ -f "$FIRST" ]; then
            cat "$FIRST"
          fi
      
      - name: СИЛОЙ МЕНЯЕМ ВЕРСИИ
        script: |
          cd $CM_BUILD_DIR
          echo "=== СИЛОВОЕ ОБНОВЛЕНИЕ ==="
          echo "Устанавливаем версию: $NEW_MARKETING_VERSION"
          echo "Устанавливаем сборку: $NEW_BUILD_NUMBER"
          
          # 1. Находим КОРНЕВОЙ Info.plist
          echo "Ищем главный Info.plist..."
          # Пробуем разные пути
          POSSIBLE_PATHS=(
            "./MemoryCard/Info.plist"
            "./ios/MemoryCard/Info.plist" 
            "./MemoryCard/Resources/Info.plist"
            "./ios/Info.plist"
            "$(find . -name "Info.plist" -type f | head -1)"
          )
          
          MAIN_PLIST=""
          for path in "${POSSIBLE_PATHS[@]}"; do
            if [ -f "$path" ]; then
              MAIN_PLIST="$path"
              echo "Нашли Info.plist: $MAIN_PLIST"
              break
            fi
          done
          
          if [ -z "$MAIN_PLIST" ]; then
            echo "ERROR: Info.plist не найден!"
            find . -name "*.plist" -type f
            exit 1
          fi
          
          # 2. Показываем текущие значения
          echo "Текущие значения в $MAIN_PLIST:"
          CURRENT_V=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$MAIN_PLIST" 2>/dev/null || echo "НЕ НАЙДЕН")
          CURRENT_B=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$MAIN_PLIST" 2>/dev/null || echo "НЕ НАЙДЕН")
          echo "  Версия: $CURRENT_V"
          echo "  Сборка: $CURRENT_B"
          
          # 3. СИЛОЙ меняем значения
          echo "Меняем значения..."
          
          # Удаляем старые ключи (если есть)
          /usr/libexec/PlistBuddy -c "Delete :CFBundleShortVersionString" "$MAIN_PLIST" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Delete :CFBundleVersion" "$MAIN_PLIST" 2>/dev/null || true
          
          # Добавляем новые
          /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $NEW_MARKETING_VERSION" "$MAIN_PLIST"
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $NEW_BUILD_NUMBER" "$MAIN_PLIST"
          
          # 4. Проверяем
          echo "Проверяем результат:"
          FINAL_V=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$MAIN_PLIST")
          FINAL_B=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$MAIN_PLIST")
          echo "  Финальная версия: $FINAL_V"
          echo "  Финальная сборка: $FINAL_B"
          
          if [ "$FINAL_V" = "$NEW_MARKETING_VERSION" ] && [ "$FINAL_B" = "$NEW_BUILD_NUMBER" ]; then
            echo "✅ УСПЕХ: Версии установлены правильно!"
          else
            echo "❌ ОШИБКА: Версии не совпадают!"
            exit 1
          fi
          
          # 5. Меняем ВСЕ остальные Info.plist на всякий случай
          echo "Обновляем остальные Info.plist файлы..."
          find . -name "Info.plist" -type f | while read plist; do
            if [ "$plist" != "$MAIN_PLIST" ]; then
              echo "  Также обновляем: $plist"
              /usr/libexec/PlistBuddy -c "Delete :CFBundleShortVersionString" "$plist" 2>/dev/null || true
              /usr/libexec/PlistBuddy -c "Delete :CFBundleVersion" "$plist" 2>/dev/null || true
              /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $NEW_MARKETING_VERSION" "$plist" 2>/dev/null || true
              /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $NEW_BUILD_NUMBER" "$plist" 2>/dev/null || true
            fi
          done
      
      - name: Build IPA for App Store
        script: |
          echo "=== СОБИРАЕМ IPA ==="
          echo "Ожидаем: Версия $NEW_MARKETING_VERSION, Сборка $NEW_BUILD_NUMBER"
          
          xcode-project build-ipa \
            --project "MemoryCard.xcodeproj" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: true
