workflows:
  memory-card-workflow:
    name: Memory Card iOS Release
    max_build_duration: 120

    environment:
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.MindForge

      vars:
        BUNDLE_ID: "com.MindForge"
        XCODE_SCHEME: "MemoryCard"
        APP_STORE_APPLE_ID: 6757203309

      ios:
        version: 1.0.1+1

    scripts:
      - name: Install CocoaPods
        script: |
          gem install cocoapods
          pod install

      - name: Build archive
        script: |
          xcodebuild \
            -workspace MemoryCard.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/MemoryCard.xcarchive \
            archive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath build/MemoryCard.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa

    artifacts:
      - build/ipa/*.ipa

    publishing:
      app_store_connect:
        apple_id: $APP_STORE_APPLE_ID
        submit_to_testflight: true
