workflows:
  memory-card-workflow:
    name: MemoryCard
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Memory Card API
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.MindForge
      vars:
        BUNDLE_ID: "com.MindForge"
        XCODE_SCHEME: "MemoryCard"
        APP_STORE_APPLE_ID: 6757203309
        NEW_MARKETING_VERSION: "1.2"
        NEW_BUILD_NUMBER: "2"
      xcode: latest
    scripts:
      - name: Set up provisioning profiles
        script: xcode-project use-profiles
      
      - name: Update versions
        script: |
          cd $CM_BUILD_DIR
          echo "Setting version to: $NEW_MARKETING_VERSION"
          echo "Setting build to: $NEW_BUILD_NUMBER"
          
          # Find main Info.plist
          PLIST=$(find . -name "Info.plist" -type f | head -1)
          echo "Found: $PLIST"
          
          # Force update
          /usr/libexec/PlistBuddy -c "Delete :CFBundleShortVersionString" "$PLIST" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Delete :CFBundleVersion" "$PLIST" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $NEW_MARKETING_VERSION" "$PLIST"
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $NEW_BUILD_NUMBER" "$PLIST"
          
          echo "Result:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST"
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST"
      
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "MemoryCard.xcodeproj" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: true
