workflows:
  memory-card-workflow:
    name: MemoryCard
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Memory Card API
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.MindForge
      vars:
        BUNDLE_ID: "com.MindForge"
        XCODE_SCHEME: "MemoryCard"
        APP_STORE_APPLE_ID: 6757203309
        # Явно задаем новые версии
        NEW_MARKETING_VERSION: "1.1"
        NEW_BUILD_NUMBER: "2"
      xcode: latest
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      
      - name: UPDATE VERSIONS IN PROJECT
        script: |
          cd $CM_BUILD_DIR
          echo "=== UPDATING VERSIONS ==="
          echo "New marketing version: $NEW_MARKETING_VERSION"
          echo "New build number: $NEW_BUILD_NUMBER"
          
          # Способ 1: Находим и обновляем все Info.plist
          echo "1. Updating Info.plist files..."
          find . -name "Info.plist" -type f | while read plist; do
            echo "Found: $plist"
            
            # Получаем текущие значения
            OLD_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$plist" 2>/dev/null || echo "1.0")
            OLD_BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$plist" 2>/dev/null || echo "1")
            echo "  Current: $OLD_VERSION (build: $OLD_BUILD)"
            
            # Устанавливаем новые значения
            /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $NEW_MARKETING_VERSION" "$plist" 2>/dev/null || true
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD_NUMBER" "$plist" 2>/dev/null || true
            
            # Проверяем
            NEW_VERSION_CHECK=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$plist" 2>/dev/null || echo "ERROR")
            NEW_BUILD_CHECK=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$plist" 2>/dev/null || echo "ERROR")
            echo "  Updated: $NEW_VERSION_CHECK (build: $NEW_BUILD_CHECK)"
            echo "  ---"
          done
          
          # Способ 2: Обновляем через xcodebuild settings
          echo "2. Updating via xcodebuild settings..."
          
          # Находим xcodeproj файл
          XCODEPROJ=$(find . -name "*.xcodeproj" -type d | head -1)
          if [ -d "$XCODEPROJ" ]; then
            echo "Found project: $XCODEPROJ"
            
            # Обновляем настройки проекта через xcodebuild
            xcodebuild -project "$XCODEPROJ" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              MARKETING_VERSION="$NEW_MARKETING_VERSION" \
              CURRENT_PROJECT_VERSION="$NEW_BUILD_NUMBER" 2>/dev/null || echo "xcodebuild settings update completed"
          fi
          
          echo "=== VERIFICATION ==="
          echo "Checking final versions:"
          
          # Проверяем через xcodebuild settings
          xcodebuild -project "MemoryCard.xcodeproj" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -showBuildSettings 2>/dev/null | grep -E "MARKETING_VERSION|CURRENT_PROJECT_VERSION" | head -10 || true
          
          # Проверяем первый Info.plist
          FIRST_PLIST=$(find . -name "Info.plist" -type f | head -1)
          if [ -f "$FIRST_PLIST" ]; then
            echo "First Info.plist:"
            echo "  Version: $(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$FIRST_PLIST" 2>/dev/null || echo 'ERROR')"
            echo "  Build: $(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$FIRST_PLIST" 2>/dev/null || echo 'ERROR')"
          fi
      
      - name: Build ipa for distribution
        script: |
          echo "=== BUILDING IPA ==="
          echo "Building with version: $NEW_MARKETING_VERSION ($NEW_BUILD_NUMBER)"
          
          # Собираем IPA через xcode-project с правильными аргументами
          # НЕ используем --args, вместо этого устанавливаем переменные окружения
          export MARKETING_VERSION="$NEW_MARKETING_VERSION"
          export CURRENT_PROJECT_VERSION="$NEW_BUILD_NUMBER"
          
          xcode-project build-ipa \
            --project "MemoryCard.xcodeproj" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
