workflows:
  memory-card-workflow:
    name: MemoryCard
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Memory Card API
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.MindForge
      vars:
        BUNDLE_ID: "com.MindForge"
        XCODE_SCHEME: "MemoryCard"
        APP_STORE_APPLE_ID: 6757203309
        # Новые версии - 1.2 и автоматический build number
        NEW_MARKETING_VERSION: "1.2"
      xcode: latest
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      
      - name: GET LATEST BUILD NUMBER
        script: |
          cd $CM_BUILD_DIR
          echo "=== GETTING LATEST BUILD NUMBER ==="
          
          # Получаем последний build number из App Store Connect
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID" 2>/dev/null || echo "0")
          echo "Latest build number in App Store Connect: $LATEST_BUILD_NUMBER"
          
          # Увеличиваем на 1
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          echo "New build number will be: $NEW_BUILD_NUMBER"
          
          # Экспортируем переменную для следующего шага
          export NEW_BUILD_NUMBER
      
      - name: UPDATE VERSIONS TO 1.2
        script: |
          cd $CM_BUILD_DIR
          echo "=== UPDATING TO VERSION $NEW_MARKETING_VERSION ==="
          echo "Setting marketing version to: $NEW_MARKETING_VERSION"
          echo "Setting build number to: $NEW_BUILD_NUMBER"
          
          # 1. Обновляем все Info.plist файлы
          echo "=== Updating ALL Info.plist files ==="
          find . -name "Info.plist" -type f | while read PLIST; do
            echo "Processing: $PLIST"
            
            if [ -f "$PLIST" ]; then
              # Получаем текущие значения
              CURRENT_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST" 2>/dev/null || echo "1.1")
              CURRENT_BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST" 2>/dev/null || echo "2")
              echo "  Current: version=$CURRENT_VERSION, build=$CURRENT_BUILD"
              
              # Устанавливаем новые значения
              /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $NEW_MARKETING_VERSION" "$PLIST" 2>/dev/null && echo "  ✓ Set version to $NEW_MARKETING_VERSION"
              /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD_NUMBER" "$PLIST" 2>/dev/null && echo "  ✓ Set build to $NEW_BUILD_NUMBER"
              
              # Проверяем
              CHECK_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST" 2>/dev/null || echo "ERROR")
              CHECK_BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST" 2>/dev/null || echo "ERROR")
              echo "  Updated: version=$CHECK_VERSION, build=$CHECK_BUILD"
            else
              echo "  ✗ File not found"
            fi
            echo "  ---"
          done
          
          # 2. Обновляем через agvtool
          echo "=== Updating via agvtool ==="
          agvtool new-marketing-version "$NEW_MARKETING_VERSION" 2>/dev/null || echo "agvtool marketing version completed"
          agvtool new-version -all "$NEW_BUILD_NUMBER" 2>/dev/null || echo "agvtool build version completed"
          
          echo "=== FINAL VERIFICATION ==="
          echo "Agvtool reports:"
          agvtool what-marketing-version 2>/dev/null || echo "Cannot get marketing version"
          agvtool what-version 2>/dev/null || echo "Cannot get build version"
      
      - name: Build IPA for App Store
        script: |
          echo "=== BUILDING FOR APP STORE ==="
          echo "Version: $NEW_MARKETING_VERSION"
          echo "Build: $NEW_BUILD_NUMBER"
          
          xcode-project build-ipa \
            --project "MemoryCard.xcodeproj" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        # НЕ отправляем в TestFlight
        submit_to_testflight: false
        # Автоматически отправляем на модерацию в App Store
        submit_to_app_store: true
